"use client";
//import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider as UrqlProvider } from "urql";
import urqlClient from "@/lib/urqlClient";
// import { appWithTranslation } from "next-i18next";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UrqlProvider value={urqlClient}>{children}</UrqlProvider>
      </body>
    </html>
  );
}

export default RootLayout;
